name: 'Terraform Build Actions'

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VITE_TINYMCE_KEY: ${{ env.VITE_TINYMCE_KEY }}
      VITE_GRMLY_KEY : ${{ env.VITE_GRMLY_KEY }}
      VITE_API_SERVER: ${{ env.VITE_API_SERVER }}
      TF_VAR_ssh_key: ${{ env.TF_VAR_ssh_key }}
      TF_VAR_GOOGLE_CLIENT_ID: ${{ secrets.TF_VAR_GOOGLE_CLIENT_ID }}
      TF_VAR_GOOGLE_CLIENT_SK:  ${{ secrets.TF_VAR_GOOGLE_CLIENT_SK }}
      TF_VAR_db_username: ${{ env.TF_VAR_db_username }}
      TF_VAR_db_password: ${{ env.TF_VAR_db_password }}
      TF_VAR_subnet_id_1: ${{ env.TF_VAR_subnet_id_1 }}
      TF_VAR_subnet_id_2: ${{ env.TF_VAR_subnet_id_2 }}
      TF_VAR_domain_name: ${{ env.TF_VAR_domain_name }}
      TF_VAR_bucket_name: ${{ env.TF_VAR_bucket_name }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build application
        run: make build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VITE_TINYMCE_KEY: ${{ env.VITE_TINYMCE_KEY }}
      VITE_GRMLY_KEY : ${{ env.VITE_GRMLY_KEY }}
      VITE_API_SERVER: ${{ env.VITE_API_SERVER }}
      TF_VAR_ssh_key: ${{ env.TF_VAR_ssh_key }}
      TF_VAR_GOOGLE_CLIENT_ID: ${{ secrets.TF_VAR_GOOGLE_CLIENT_ID }}
      TF_VAR_GOOGLE_CLIENT_SK:  ${{ secrets.TF_VAR_GOOGLE_CLIENT_SK }}
      TF_VAR_db_username: ${{ env.TF_VAR_db_username }}
      TF_VAR_db_password: ${{ env.TF_VAR_db_password }}
      TF_VAR_subnet_id_1: ${{ env.TF_VAR_subnet_id_1 }}
      TF_VAR_subnet_id_2: ${{ env.TF_VAR_subnet_id_2 }}
      TF_VAR_domain_name: ${{ env.TF_VAR_domain_name }}
      TF_VAR_bucket_name: ${{ env.TF_VAR_bucket_name }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: AWS Config
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: terraform plan
        run: make tf-plan
      - name: terraform apply
        run: make tf-deploy